export const workList = [
  {
    id: 1,
    title: 'geld, muss man.',
    link: 'https://geldmussman.onrender.com/',
    description: 'finance tracker app',
    tech: 'react.js, node.js, express.js, mongoDB',
    code: 'https://github.com/escapingSamsara/financeApp-Project-Github',
    image: 'workListImages/geldmussman.png',
  },
  {
    id: 2,
    title: 'clarityUI',
    link: 'https://escapingsamsara.github.io/ClarityUI_concept/',
    description: 'design blog landing page',
    tech: 'react.js',
    code: 'https://github.com/escapingSamsara/ClarityUI_concept',
    image: 'workListImages/clarityUI.png',
  },
  {
    id: 3,
    title: 'cloudstash',
    link: '#',
    description: 'crypto wallet landing page',
    tech: 'react.js',
    code: '#',
    image: 'workListImages/cloudstash_wallet.png',
  },
  {
    id: 4,
    title: 'cryptonic.wallet',
    link: '#',
    description: 'crypto wallet landing page',
    tech: 'react.js',
    code: '#',
    image: 'workListImages/cryptonic_wallet.png',
  },
  {
    id: 5,
    title: 'Lor3mPixum',
    link: 'https://escapingsamsara.github.io/lor3mPixum/',
    description: 'pixel game dev company portfolio',
    tech: 'vanilla js',
    code: 'https://github.com/escapingSamsara/lor3mPixum',
    image: 'workListImages/lor3mPixum.png',
  },
  {
    id: 6,
    title: 'todo or not todo?',
    link: 'https://github.com/escapingSamsara/todo-list-react',
    description: 'todo list widget for aesthetes',
    tech: 'react.js',
    code: 'https://escapingsamsara.github.io/todo-list-react/',
    image: 'workListImages/todoOrNotTodo.png',
  },
]
